from enum import Enum
from pydantic import BaseModel


class SignalDirection(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"


class Signal(BaseModel):
    """Trading signal generated by the analyzer."""
    symbol: str
    direction: SignalDirection
    price: float
    change_15m: float       # % price change over 15 minutes
    rsi_1h: float           # RSI value on 1h timeframe
    rsi_15m: float          # RSI value on 15m timeframe
    chart_url: str | None = None
    telegram_sent: bool = False